export const SCHEMA_STATEMENTS: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS cards (
    id                   TEXT PRIMARY KEY,
    project              TEXT NOT NULL,
    title                TEXT NOT NULL,
    status               TEXT NOT NULL,
    type                 TEXT NOT NULL,
    version              INTEGER NOT NULL,
    position             INTEGER NOT NULL,
    priority             TEXT NOT NULL DEFAULT 'medium',
    tags                 TEXT NOT NULL DEFAULT '[]',
    due_date             TEXT,
    assigned_to          TEXT,
    owner                TEXT,
    agent_notes          TEXT,
    total_input_tokens   INTEGER NOT NULL DEFAULT 0,
    total_output_tokens  INTEGER NOT NULL DEFAULT 0,
    created_at           TEXT NOT NULL,
    updated_at           TEXT NOT NULL,
    created_by           TEXT NOT NULL,
    updated_by           TEXT NOT NULL,
    file_hash            TEXT NOT NULL,
    file_basename        TEXT NOT NULL DEFAULT '',
    archived             INTEGER NOT NULL DEFAULT 0
  )`,
  // idx_project_basename is created by the file_basename migration in
  // database.ts — must run after ALTER TABLE on legacy DBs.
  `CREATE INDEX IF NOT EXISTS idx_project_status   ON cards(project, status)`,
  `CREATE INDEX IF NOT EXISTS idx_project_position ON cards(project, status, position)`,
  `CREATE INDEX IF NOT EXISTS idx_project_type     ON cards(project, type)`,
  `CREATE INDEX IF NOT EXISTS idx_due_date         ON cards(due_date)`,
  `CREATE INDEX IF NOT EXISTS idx_assigned_to      ON cards(assigned_to)`,
  `CREATE TABLE IF NOT EXISTS token_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    ts              TEXT NOT NULL,
    op              TEXT NOT NULL,
    card_id         TEXT NOT NULL,
    card_type       TEXT NOT NULL,
    actor           TEXT NOT NULL,
    model           TEXT NOT NULL,
    input_tokens    INTEGER NOT NULL,
    output_tokens   INTEGER NOT NULL,
    project         TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS idx_token_log_ts       ON token_log(ts)`,
  `CREATE INDEX IF NOT EXISTS idx_token_log_type     ON token_log(card_type)`,
  `CREATE INDEX IF NOT EXISTS idx_token_log_model    ON token_log(model)`,
  `CREATE INDEX IF NOT EXISTS idx_token_log_project  ON token_log(project)`,
]
